# Generated by Django 3.2.9 on 2021-12-08 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeRegistration',
            fields=[
                ('Employeeid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contact_no', models.IntegerField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('designation', models.CharField(blank=True, choices=[('intern', 'Intern'), ('full_time', 'Full Time')], max_length=20)),
                ('department', models.CharField(blank=True, choices=[('software', 'Development & IT'), ('ed_tech', 'Ed-Tech'), ('marketing', 'Marketing'), ('design', 'Designing'), ('content_writing', 'Content-Writing')], max_length=20)),
                ('jobs', models.CharField(blank=True, choices=[('on_site', 'Regular'), ('WFH', 'Work From Home')], max_length=15)),
                ('date_of_joining', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timestamp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('login_time', models.DateTimeField(auto_now_add=True)),
                ('logout_time', models.DateTimeField(blank=True, null=True)),
                ('Employeeid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.employeeregistration')),
            ],
        ),
    ]
