# Generated by Django 3.2.9 on 2021-12-20 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='contact_no',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='department',
            field=models.CharField(blank=True, choices=[('Software', 'Development & IT'), ('Ed_tech', 'Ed-Tech'), ('Marketing', 'Marketing'), ('Design', 'Designing'), ('Content writing', 'Content-Writing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='designation',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Full Time', 'Full Time')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='jobs',
            field=models.CharField(blank=True, choices=[('Regular', 'Regular'), ('Work From Home', 'Work From Home')], max_length=15),
        ),
    ]
