# Generated by Django 3.2.9 on 2021-12-20 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211220_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeregistration',
            name='contact_no',
            field=models.CharField(blank=True, max_length=12, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,12}$')]),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='department',
            field=models.CharField(blank=True, choices=[('Software', 'Development & IT'), ('Ed-tech', 'Ed-Tech'), ('Marketing', 'Marketing'), ('Design', 'Designing'), ('Content_writing', 'Content-Writing')], max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeregistration',
            name='designation',
            field=models.CharField(blank=True, choices=[('Intern', 'Intern'), ('Full_time', 'Full Time')], max_length=20),
        ),
    ]
